volumes:
  db: {}

services:
  db:
    image: postgres:16.3-alpine
    container_name: ms_db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./envs/db.env
    ports:
      - '5432:5432'
    restart: unless-stopped

  auth:
    image: devmiguelangel/ms-insta-auth:latest
    container_name: ms_auth
    volumes:
      - ./services/auth:/api
    env_file:
      - ./envs/auth.env
    ports:
      - '8001:8000'
    depends_on:
      - db
    restart: unless-stopped
