volumes:
  db: {}
  db_mongo: {}

services:
  db:
    image: postgres:16.3-alpine
    container_name: ms_db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./envs/db.env
    ports:
      - '5432:5432'
    restart: unless-stopped

  mongo:
    image: mongo:7.0.12
    container_name: ms_mongo
    volumes:
      - db_mongo:/data/db
      - ./envs/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    env_file:
      - ./envs/mongo.env
    ports:
      - '27017:27017'
    restart: unless-stopped

  auth:
    image: devmiguelangel/ms-insta-auth:latest
    container_name: ms_auth
    volumes:
      - ./services/auth:/api
    env_file:
      - ./envs/auth.env
    ports:
      - '8001:8000'
    depends_on:
      - db
    restart: unless-stopped

  gateway:
    image: devmiguelangel/ms-insta-gateway:latest
    container_name: ms_gateway
    volumes:
      - ./services/gateway:/api
    env_file:
      - ./envs/gateway.env
    ports:
      - '8002:8000'
    depends_on:
      - auth
      - mongo
    restart: unless-stopped

  queue:
    image: rabbitmq:3.13-management-alpine
    container_name: ms_queue
    ports:
      - '5672:5672'
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=miguel
      - RABBITMQ_DEFAULT_PASS=secret
    # volumes:
    #   - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #   - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    restart: unless-stopped
