volumes:
  db: {}
  db_mongo: {}
  rabbitmq-data: {}

services:
  db:
    image: postgres:16.3-alpine
    container_name: ms_db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./compose/envs/db.env
    ports:
      - '5432:5432'
    restart: unless-stopped

  mongo:
    image: mongo:7.0.12
    container_name: ms_mongo
    volumes:
      - db_mongo:/data/db
      - ./compose/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    env_file:
      - ./compose/envs/mongo.env
    ports:
      - '27017:27017'
    restart: unless-stopped

  auth:
    image: devmiguelangel/ms-insta-auth:latest
    container_name: ms_auth
    volumes:
      - ./services/auth:/api
    env_file:
      - ./compose/envs/auth.env
    ports:
      - '8001:8000'
    depends_on:
      - db
    restart: unless-stopped

  gateway:
    image: devmiguelangel/ms-insta-gateway:latest
    container_name: ms_gateway
    volumes:
      - ./services/gateway:/api
    env_file:
      - ./compose/envs/gateway.env
    ports:
      - '8002:8000'
    depends_on:
      - auth
      - mongo
      - rabbitmq
    restart: unless-stopped

  converter:
    image: devmiguelangel/ms-insta-converter:latest
    container_name: ms_converter
    volumes:
      - ./services/converter:/api
    env_file:
      - ./compose/envs/converter.env
    ports:
      - '8003:8000'
    depends_on:
      - mongo
      - rabbitmq
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: ms_rabbitmq
    ports:
      - '5672:5672'
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=miguel
      - RABBITMQ_DEFAULT_PASS=secret
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    #   - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    restart: unless-stopped
