apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-converter-config
data:
  DB_USER: miguel
  DB_HOST: mongo
  DB_PORT: '27017'
  DB_NAME: media
  RABBITMQ_HOST: ms-rabbitmq
  RABBITMQ_PORT: '5672'
  RABBITMQ_USER: miguel
  VIDEO_QUEUE: VIDEOS
  AUDIO_QUEUE: AUDIOS

