apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-notification-config
data:
  RABBITMQ_HOST: ms-rabbitmq
  RABBITMQ_PORT: '5672'
  RABBITMQ_USER: miguel
  VIDEO_QUEUE: VIDEOS
  AUDIO_QUEUE: AUDIOS

